name: Update README

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run update script
        run: node update-readme.js
      - name: Commit changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add README.md
          git commit -m "Update README with latest data"
          git push
